// table schema generated by introspection
import {
  integer,
  pgTable,
  text,
  timestamp,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";

export const files = pgTable("files", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: varchar("name", { length: 255 }).notNull(),
  uploadDate: timestamp("upload_date").notNull().defaultNow(),
  url: varchar("url", { length: 2048 }).notNull(),
  fileType: varchar("fileType", { length: 255 }).notNull(),
  fileSize: integer("fileSize").notNull().default(0),
  fileKey: text("fileKey"),
  userId: uuid("user_id"),
});

// export const users = pgTable("users", {
//   id: uuid().primaryKey().defaultRandom(),
//   name: varchar("name", { length: 255 }).notNull(),
// });
